
import os.path

Import("env")


# SOURCES

httpsources = [

	'http.c'

	]

httpheaders = [

	'build.h', 'hashstrings.h', 'http.h', 'internal.h', 'types.h'

	]


# ADD INTERNAL FLAGS

libenv = env.Clone()
libenv.Append( CPPDEFINES=['HTTP_COMPILE=1'] )


# OUTPUTS

env['httplib'] = libenv.StaticLibrary( 'http', httpsources )


# DEPENDENCIES

#if env['toolset'] == 'gnu':
#	libenv.Depends( [ os.path.splitext( x )[0] + '.o' for x in networksources ], '#/network/network.h.gch' )


# INSTALLS

libenv.AddPostAction( 'http', libenv.Install( '#lib/${platform}${platformsuffix}/${buildprofile}', [ env['httplib'] ] ) )
